version: '3.1'

services:

  php:
    build: .
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "81:80"
    depends_on:
      - "db"

  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "6606:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sentrifugo
